node {
   
    
    stage ('Clone') {
        git url: 'https://github.com/nickgulrajani/project-examples.git'
    }
 
    stage ('Artifactory configuration') {
        
        script {
            def server = Artifactory.server 'Jfrog'

            def rtMaven = Artifactory.newMavenBuild()
            
            rtMaven.tool = 'Maven' // Tool name from Jenkins configuration
            rtMaven.deployer releaseRepo: 'example-repo-local', snapshotRepo: 'example-repo-local', server
            rtMaven.resolver releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot', server
            
            rtMaven.deployer.deployArtifacts = false // Disable artifacts deployment during Maven run

            def buildInfo = Artifactory.newBuildInfo()
            
        
       
        }
        
        
    }
 
    stage ('Test') {
        rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean test'
    }
        
    stage ('Install') {
        rtMaven.run pom: 'maven-example/pom.xml', goals: 'install', buildInfo: buildInfo
    }
 
    stage ('Deploy') {
        rtMaven.deployer.deployArtifacts buildInfo
    }
        
    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}

