node {
    def server
    def rtMaven
    def buildInfo
    
    stage ('Clone') {
        git url: 'https://github.com/nickgulrajani/project-examples.git'
    }
    
    stage('SonarQube Code analysis') {
            
              script {
                    withSonarQubeEnv('Sonar 7') {
			def sonarHome = tool 'Sonar'
                        sh '${sonarHome}/bin/sonar-scanner -D sonar-project.properties'
                    }
              }
            
    }
 
    stage ('Artifactory configuration') {
        
        script {
            server = Artifactory.server 'Jfrog'

            rtMaven = Artifactory.newMavenBuild()
            
            rtMaven.tool = 'Maven' // Tool name from Jenkins configuration
            rtMaven.deployer server: server, releaseRepo: 'example-repo-local', snapshotRepo: 'example-repo-local'
            rtMaven.resolver server: server, releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot'
            //rtMaven.deployer releaseRepo: 'example-repo-local', snapshotRepo: 'example-repo-local', server
            //rtMaven.resolver releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot', server
            
            rtMaven.deployer.deployArtifacts = false // Disable artifacts deployment during Maven run

            buildInfo = Artifactory.newBuildInfo()
            
        
       
        }
        
        
    }
 
    stage ('Test') {
        rtMaven.run pom: 'maven-example/pom.xml', goals: 'clean test'
        
    }
        
    stage ('Install') {
        rtMaven.run pom: 'maven-example/pom.xml', goals: 'install', buildInfo: buildInfo
    }
 
    stage ('Deploy') {
        rtMaven.deployer.deployArtifacts buildInfo
    }
        
    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}

