node {
    stage 'Build'
    git url: 'https://github.com/nickgulrajani/project-examples.git'

    // Obtain an Artifactory server instance, defined in Jenkins --> Manage:


    rtServer (
    id: 'jfrog',
    url: 'http://ec2-54-188-187-183.us-west-2.compute.amazonaws.com:8082/artifactory ',
    // If you're using username and password:
    username: 'admin',
    password: 'changeme'
)
    def server = jfrog 

    // Create the upload spec.
    def uploadSpec = readFile 'jenkins-examples/pipeline-examples/resources/props-upload.json'

    // Upload to Artifactory.
    def buildInfo = server.upload spec: uploadSpec

    // Create the download spec.
    def downloadSpec = readFile 'jenkins-examples/pipeline-examples/resources/props-download.json'

    // Download from Artifactory.
    server.download spec: downloadSpec, buildInfo: buildInfo

    // Publish the build to Artifactory
    server.publishBuildInfo buildInfo

    stage 'Promotion'
    def promotionConfig = [
        //Mandatory parameters
        'buildName'          : buildInfo.name,
        'buildNumber'        : buildInfo.number,
        'targetRepo'         : 'libs-release-local',

        //Optional parameters
        'comment'            : 'this is the promotion comment',
        'sourceRepo'         : 'libs-snapshot-local',
        'status'             : 'Released',
        'includeDependencies': true,
        'failFast'           : true,
        'copy'               : true
    ]

    // Promote build
    server.promote promotionConfig
}
